select
    id,
    code,
    description as name,
    organisation,
    geography,
    modified_on,
    type,
    details->>'EcotopeSystem' as ecotype_system,
    details->>'WaterSystem' as water_system,
    details->>'MonitoringNetworks' as monitoring_networks,
    details->>'Files' as files,
    details->>'Weighting' as weighting,
    details->>'TwnStatus' as twn_status,
    details->>'Symbol' as symbol,
    details->>'KrwCode' as krw_code,
    details->>'End' as end_date,
    details->>'TaxonType' as taxon_type,
    details->>'MeasurementObjects' as measurement_objects,
    details->>'TaxonAuthors' as taxon_authors,
    details->>'Reference' as referece,
    details->>'CasNumber' as cas_number,
    details->>'TaxonRank' as taxon_rank,
    details->>'Start' as start_date,
    details->>'MinValue' as min_value,
    details->>'Citation' as citation,
    details->>'TwnCode' as twn_code,
    details->>'TaxonNameNl' as taxon_name_nl,
    details->>'TaxonGroup' as taxon_group,
    details->>'ParameterType' as parameter_type,
    details->>'Version' as version,
    details->>'MaxValue' as max_value,
    details->>'ReportsToMeasurementObject' as reports_to_measurement_object,
    details->>'IsReportingMeasurementObject' as is_reporting_measurement_object
from reference
where (@access AND @where AND @skiptoken)
limit @limit
